name: "Create backend container {{NAME_ROUTE}}"

# Only trigger, when the build workflow succeeded
on:
  workflow_dispatch:
    inputs:
      package_version:
        description: 'Version to build'     
        required: true

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    steps:
      - name: Receive event
        run: echo -e "ref:${{ github.ref }}\nversion:${{ inputs.package_version }}\n"

      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}

      - name: Publish to Registry Production
        if: "!contains(inputs.package_version, 'beta')"
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          workdir: {{LOCATION}}
          pre: echo ::save-state name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
          name: vanessa-lanquetin/monorepo/{{NAME_ROUTE}}
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.NPM_TOKEN }}
          registry: docker.pkg.github.com
          tags: "latest,${{ inputs.package_version }}"
          buildargs: --build-arg NPM_TOKEN=${{secrets.NPM_TOKEN}} --build-arg PACKAGE_VERSION=${{inputs.package_version}}

      - name: Publish to Registry Prerelease
        if: "contains(inputs.package_version, 'beta')"
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          workdir: {{LOCATION}}
          pre: echo ::save-state name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
          name: vanessa-lanquetin/monorepo/{{NAME_ROUTE}}
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.NPM_TOKEN }}
          registry: docker.pkg.github.com
          tags: "prerelease,${{ inputs.package_version }}"
          buildargs: --build-arg NPM_TOKEN=${{secrets.NPM_TOKEN}} --build-arg PACKAGE_VERSION=${{inputs.package_version}}